# Machine Learning: Sesión 1 Álgebra Lineal

In [1]:
import pandas as pd
import numpy as np

### Puntos y vectores

El conjunto de datos usualmente está formador por **puntos** en un espacio $n$-dimensional. Ejemplo de punto 3D:

$$ x = (1,2,3) \; x \in \mathbb{R}^{3} $$

El conjunto de datos también puede interpretarse como un conjunto de vectores en un espacio $n$-dimensional. Un ejemplo de vector sería el siguiente:

$$ x = \begin{bmatrix} 1\\ 2\\ 3 \end{bmatrix} $$

En Python podemos declarar este vector de la siguiente forma:

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

### Forma de un vector

Los vectores tiene asociada una **forma** que es la que indica como se distribuyen las dimensiones del mismo. Para un vector columna de 3 dimensiones:

$$ shape(x) = (3) $$

Para un vector matrix de 2 filas y 3 columnas:

$$ y = \begin{bmatrix} 1 & 2 & 3\\ 4 & 5 & 6\end{bmatrix} $$

$$ shape(y) = (2,3) $$

En Python los vectores multidimensionales se declaran así:

In [3]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

La **forma** de un vector es una propiedad de clase:

In [4]:
print(y.shape[0])
print(x.shape)

2
(3,)


### Dimensión de un vector

La **dimensión** de un vector viene dada por la operación $dim(x)$. La operación $dim(x)$ se puede expresar como el productorio de la forma de un vector.

$$ dim(x) = \prod_{d\in shape(x)} d $$


Ejemplos:

$$ dim(x) = 3 $$

$$ dim(y) = 2 \cdot  3 = 6 $$

In [5]:
np.prod(y.shape)

6

### Subíndice de un vector

Podemos acceder a las coordenadas de un vector mediante el uso de subíndices sobre la variable.

$$ x_i $$
$$ y_{i,j} $$

Ejemplos:

$$ x_2 = 2 $$
$$ y_{2,3} = 6 $$

Los subíndices en Python a igual que en la mayoría de lenguajes comienzan en $0$ en lugar de $1$ y se expresan mediante el operador de corchetes:

In [6]:
print(x[1])
print(y[1,2])

2
6


### Norma de un vector

La norma de un vector nos indica la distancia al origen de coordenadas de dicho vector o lo que es lo mismo el módulo.

$$ ||x||_2 = \sqrt{\sum_{i} x_i^{2}} $$
$$ ||y||_2 = \sqrt{\sum_{i,j} y_{i,j}^{2}} $$

Ejemplo:

$$ ||x|| = \sqrt{1^2+2^2+3^2} = \sqrt{14} = 3.741657386773941 $$
$$ ||y|| = 9.539392014169456 $$

En Python encontramos la normal en el submódulo de funciones de Algebra Lineal:

In [7]:
np.linalg.norm(y)

9.539392014169456

### Producto de un vector

El producto algebráico de dos vectores:

$$ x \cdot z = \sum_{i} x_i \cdot z_i \in \mathbb{R} $$

El producto geométrico de dos vectores:

$$ x \cdot z = ||x|| \cdot ||z|| \cdot \cos(\theta) $$

Ejemplo:

$$ x = [1,2,3]^T $$
$$ z = [4,5,6]^T $$
$$ x \cdot z = 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 = 32 $$

En Python se puede computar haciendo uso del método dot de la clase:

In [8]:
x = np.array([1,2,3])
z = np.array([4,5,6])
print(x.dot(z))
print((x * z).sum())
theta = (x / np.linalg.norm(x)).dot(z / np.linalg.norm(z))
print(np.linalg.norm(x) * np.linalg.norm(z) * theta)

32
32
32.0


Otra operación muy utilizada es el producto elemento-elemento, que se denota mediante el símbolo $ \circ $.

Sean $x,y \in \mathbb{R}^{n}$
$$ x \circ z = \begin{bmatrix}x_1 \cdot z_1\\ x_2 \cdot z_2\\ ...\\ x_n \cdot z_n\end{bmatrix} \in \mathbb{R}^{n} $$

En Python se puede computar haciendo uso del operador *:

In [9]:
x = np.array([1,2,3])
z = np.array([4,5,6])
x * z

array([ 4, 10, 18])

### Producto matricial 2D

Sean $A \in \mathbb{R}^{m \times n}$ y $B \in \mathbb{R}^{n \times p}$ dos matrices bidimensionales, enconces se define el producto como:

$$ A \cdot B \in \mathbb{R}^{m \times p} $$
donde,
$$ (A \cdot B)_{i,j} = \sum_{k=1}^{n} a_{i,k} \cdot b_{k,j} $$

En Python se pueden declarar matrices y computar su producto de la siguiente forma:

In [10]:
m = 3
n = 4
p = 2
A = np.random.rand(m,n)
print(A)
print(A.shape)
B = np.random.rand(n,p)
print(B)
print(B.shape)

C = A.dot(B)
print(C)
print(C.shape)

[[0.2620965  0.78834198 0.11666693 0.59005301]
 [0.67658066 0.06831    0.14013539 0.26348598]
 [0.18570828 0.36536673 0.77320317 0.52131375]]
(3, 4)
[[0.53042799 0.49492047]
 [0.89916935 0.38850822]
 [0.09515178 0.08108483]
 [0.85867507 0.55121035]]
(4, 2)
[[1.36564114 0.7706975 ]
 [0.65988256 0.51799167]
 [0.94824221 0.58390739]]
(3, 2)


### Producto matricial 3D

Sean $A \in \mathbb{R}^{m \times n \times r}$ y $B \in \mathbb{R}^{n \times d \times r}$ dos matrices tridimensionales, entonces se define el producto como:

$$ A \times B \in \mathbb{R}^{m \times d \times r} $$

En Python se pueden declarar matrices y computar su producto 3D de la siguiente forma:

In [11]:
import numpy as np

D,M,N,R = 1,2,3,4
A = np.random.rand(M,N,R)
B = np.random.rand(N,D,R)
C = np.einsum('mnr,ndr->mdr', A, B)
print(C.shape)

(2, 1, 4)


NumPy en una biblioteca de vectores multidimensionales que permite trabajar con matrices de mas de dos coordenadas en la forma.

In [12]:
X = np.random.rand(1,2,3,4,5)
X.shape

(1, 2, 3, 4, 5)

La mayoría de operaciones pueden aplicarse con independencia de la dimensionalidad de trabajo.

In [13]:
(X * X).shape

(1, 2, 3, 4, 5)

### Métodos de factoría

¿Cómo podemos crear matrices de una forma rápida?

Crear un vector en un rango de valores:

In [14]:
x = np.arange(3,10,2)
x

array([3, 5, 7, 9])

Crear una matriz uniformemente distribuida en el intervalo $[0,1]$:

In [15]:
X = np.random.rand(3,4)
X

array([[0.65548885, 0.28416989, 0.54674888, 0.40231129],
       [0.80270333, 0.57880115, 0.92173674, 0.61081377],
       [0.53193788, 0.11923362, 0.31588408, 0.35805931]])

Crea una matriz identidad de cualquier dimensión:

In [16]:
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Crear una matriz de zeros:

In [17]:
X = np.zeros((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Crear una matriz de unos:

In [18]:
X = np.ones((3,4))
X

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Consultas avanzas por índices

¿Cómo obtener la diagonal de una matriz mediante índices?

In [19]:
X = np.random.rand(5,5)
print(X)
X[np.arange(0,5),np.arange(0,5)]

[[0.98095206 0.05794687 0.98766211 0.7628804  0.35052473]
 [0.53888922 0.01382501 0.91058295 0.90475043 0.02892106]
 [0.51938985 0.42382222 0.79292435 0.44193552 0.97774314]
 [0.67876866 0.03696018 0.89406935 0.34564465 0.67437005]
 [0.68012674 0.77766106 0.2973828  0.7958787  0.14810889]]


array([0.98095206, 0.01382501, 0.79292435, 0.34564465, 0.14810889])

In [20]:
X = np.random.randint(low = 0, high = 10, size = (10,5))
print(X)

[[1 4 0 1 3]
 [0 8 1 0 4]
 [0 3 4 3 4]
 [0 7 1 1 1]
 [4 6 6 0 9]
 [2 4 5 6 1]
 [8 4 5 8 8]
 [5 3 7 6 3]
 [8 4 4 5 2]
 [9 0 5 8 4]]


Mostrar todas las filas en la que la primera columna sea mayor que 3.

In [21]:
X[X[:,0] > 3]

array([[4, 6, 6, 0, 9],
       [8, 4, 5, 8, 8],
       [5, 3, 7, 6, 3],
       [8, 4, 4, 5, 2],
       [9, 0, 5, 8, 4]])

Mostrar todas las columnas que su media sea mayor que 6.

In [22]:
X.mean(axis = 0)
X.shape

(10, 5)

In [23]:
X[:,X.mean(axis = 0) > 6]

array([], shape=(10, 0), dtype=int32)

In [24]:
X = np.random.rand(5,5)
X

array([[0.30721466, 0.5119455 , 0.20039097, 0.9565932 , 0.91628224],
       [0.91314436, 0.96423063, 0.76960368, 0.84850671, 0.02866106],
       [0.29786719, 0.23406587, 0.29967254, 0.65305394, 0.48079756],
       [0.0127373 , 0.67190139, 0.88066499, 0.88695711, 0.42894617],
       [0.33221568, 0.22689549, 0.65802827, 0.31962448, 0.06305752]])

¿En qué coordenadas se encuentra el máximo de la matriz X?

In [25]:
np.unravel_index(X.argmax(), X.shape)

(1, 1)

Calcular percentiles de conjuntos:

In [26]:
np.percentile(X, 0.25)

0.013692723079126824

In [27]:
X = np.random.rand(3,2)
X

array([[0.78978993, 0.24223657],
       [0.30218318, 0.49691334],
       [0.43840966, 0.08827853]])

Calcular la varianza de las columnas:

In [28]:
X.var(axis = 0)

array([0.04219845, 0.02839397])

Calcular la varianza de las filas:

In [29]:
X.var(axis = 1)

array([0.07495367, 0.00947996, 0.03064795])

In [30]:
X.T.T

array([[0.78978993, 0.24223657],
       [0.30218318, 0.49691334],
       [0.43840966, 0.08827853]])

Agregar una fila más a un conjunto de datos

In [31]:
print(X)
Y = np.vstack((np.array([3,4]),X))
Y

[[0.78978993 0.24223657]
 [0.30218318 0.49691334]
 [0.43840966 0.08827853]]


array([[3.        , 4.        ],
       [0.78978993, 0.24223657],
       [0.30218318, 0.49691334],
       [0.43840966, 0.08827853]])

In [50]:
n = 4
m = 25
X = np.random.rand(m,n)
X

array([[0.5837322 , 0.84594006, 0.34260897, 0.19433426],
       [0.97798159, 0.1412729 , 0.15775251, 0.19022168],
       [0.39259429, 0.71139166, 0.32912447, 0.34758384],
       [0.05649843, 0.52215662, 0.59085382, 0.03820431],
       [0.53248062, 0.83044541, 0.04234408, 0.07117174],
       [0.92145575, 0.7926362 , 0.0165094 , 0.34552023],
       [0.78764021, 0.84296928, 0.12765573, 0.75782947],
       [0.0957084 , 0.05668056, 0.96847666, 0.97537199],
       [0.43658782, 0.18974116, 0.34983213, 0.5996571 ],
       [0.25457322, 0.12240757, 0.7427773 , 0.95112124],
       [0.25728529, 0.45770981, 0.91870782, 0.71528936],
       [0.95945385, 0.21672437, 0.20707578, 0.03231521],
       [0.45915718, 0.06984681, 0.04182697, 0.73509831],
       [0.79445124, 0.91317239, 0.69665685, 0.95611342],
       [0.26909916, 0.63944476, 0.2135892 , 0.8509043 ],
       [0.06252714, 0.57801302, 0.01494648, 0.19540662],
       [0.82261735, 0.29053978, 0.38416717, 0.68761187],
       [0.51656667, 0.13464105,

### Descomposición en Valores Singulares SVD

$$ X = U \cdot S \cdot V $$

donde,

$ X \in \mathbb{R}^{m \times n}$

$ U \in \mathbb{R}^{n \times m}$ es ortogonal.

$ S \in \mathbb{R}^{m \times m}$ es diagonal.

$ V \in \mathbb{R}^{m \times m}$ es ortogonal.

Los elementos de la diagonal de $S$ se les denomina **valores singulares**.

Las columnas de $U$ son las direcciones principales de salida.

Las columnas de $V$ son las direcciones principales de entrada.

### Matrices Ortogonales

Sea $X$ una matriz ortogonal entonces:

$ X \cdot X.T = I $

Tanto las filas como las columnas de $ X $ son vectores unitarios.

In [51]:
X.shape

(25, 4)

In [39]:
u,s,v = np.linalg.svd(X, full_matrices = False)

In [40]:
u.shape

(200, 4)

In [41]:
s.shape

(4,)

In [48]:
s / s.sum()

array([0.56817937, 0.1533099 , 0.1485967 , 0.12991402])

In [42]:
v.shape

(4, 4)

In [46]:
((u * s).dot(v) - X).sum()

-2.989409934872622e-13

In [53]:
X.dot(v[:,:3])

array([[ 0.20658319, -1.0167062 ,  0.09359733],
       [-0.36322287, -0.75758675, -0.44892336],
       [ 0.27732659, -0.89231984,  0.03718488],
       [ 0.07599118, -0.64125777,  0.45200184],
       [ 0.29986436, -0.77127148,  0.02850545],
       [ 0.21240596, -1.04812524, -0.35005975],
       [ 0.42793934, -1.21511646, -0.45583505],
       [-0.02956677, -0.97067953, -0.10037797],
       [ 0.00886813, -0.74712057, -0.31537366],
       [ 0.02491741, -0.9582933 , -0.25664666],
       [ 0.07167739, -1.14468013,  0.09872399],
       [-0.39019213, -0.75590177, -0.29186554],
       [ 0.10682791, -0.57788415, -0.61315217],
       [ 0.30655226, -1.63997792, -0.2531035 ],
       [ 0.54220844, -0.91034843, -0.2920203 ],
       [ 0.4203524 , -0.41655536,  0.07283021],
       [-0.0879017 , -1.05919515, -0.49843858],
       [-0.07762463, -0.71640772, -0.35154707],
       [ 0.16028554, -0.57504119, -0.58634402],
       [-0.09856293, -1.04479392, -0.53765397],
       [-0.31632296, -0.57378395,  0.126