In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Mínimos Cuadrados

In [2]:
# Número de características
n = 10
# Número de datos
m = 100

In [3]:
b = np.random.randint(-5,5,n)
print(b)
print(b.shape)
X = np.random.rand(m,n)
print(X.shape)
y = X.dot(b) + np.random.rand(m) - 0.5
print(y.shape)

[ 4  1 -5  3 -3 -5  2  1 -5 -3]
(10,)
(100, 10)
(100,)


In [4]:
b

array([ 4,  1, -5,  3, -3, -5,  2,  1, -5, -3])

$$ b = (X.T * X)^{-1} * X.T * y $$

In [5]:
b_estimate = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

In [6]:
b_estimate

array([ 4.17264416,  0.93843607, -5.18753214,  3.13672629, -2.83797436,
       -4.99155339,  2.00284565,  0.8606035 , -5.12480977, -3.05077703])